### PR TITLE
cut user skills from user profile

### PR DESCRIPTION
**Pull request by IgorPolyakov**

### CODE REVIEW

**Comment by IgorPolyakov** [comment]
Test it, before code merge
Maybe i forgot something)

**Comment by sea-kg** [comment]
I have not success build:

frontend.git$ ./start-dev.sh 
                                                                                          
Date: 2019-07-11T06:35:35.440Z
Hash: b64a8cd7a186b9fd89d5
Time: 4705ms
chunk {main} main.js, main.js.map (main) 1.92 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 145 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 414 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.3 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in src/app/modal-dialog-sign-in/modal-dialog-sign-in.component.ts(18,4): error TS2554: Expected 2 arguments, but got 1.
src/app/modal-dialog-sign-in/modal-dialog-sign-in.component.ts(19,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/automation-ussr/automation-ussr.component.ts(14,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/automation-ussr/automation-ussr.component.ts(15,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/automation-ussr/automation-ussr.component.ts(16,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/chat/chat.component.ts(14,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/chat/chat.component.ts(15,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/feedback/feedback.component.ts(14,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/feedback/feedback.component.ts(15,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/feedback/feedback.component.ts(16,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(19,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(20,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(21,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(22,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(23,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(24,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(25,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/quest-proposal/quest-proposal.component.ts(26,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/registration/registration.component.ts(16,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/registration/registration.component.ts(17,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/reset-password/reset-password.component.ts(16,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/server-api/server-api.component.ts(3,10): error TS2305: Module '"../../../../node_modules/@angular/platform-browser/platform-browser"' has no exported member 'DOCUMENT'.
src/app/pages/user-change-password/user-change-password.component.ts(18,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/user-change-password/user-change-password.component.ts(19,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/user-profile/user-profile.component.ts(8,10): error TS2724: Module '"../user-skills/user-skills.component"' has no exported member 'UserSkilsComponent'. Did you mean 'UserSkillsComponent'?
src/app/pages/user-profile/user-profile.component.ts(34,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/user-profile/user-profile.component.ts(35,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/user-profile/user-profile.component.ts(36,4): error TS2554: Expected 2 arguments, but got 1.
src/app/pages/user-skills/user-skills.component.ts(15,14): error TS2339: Property '_fhq' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(20,12): error TS2339: Property 'userSkills' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(25,10): error TS2339: Property '_fhq' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(26,22): error TS2339: Property 'userId' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(32,10): error TS2339: Property 'userSkills' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(39,12): error TS2339: Property 'userSkills' does not exist on type 'UserSkillsComponent'.
src/app/pages/user-skills/user-skills.component.ts(41,10): error TS2339: Property '_cdr' does not exist on type 'UserSkillsComponent'.
src/app/services/fhq.service.ts(2,10): error TS2305: Module '"../../../node_modules/@angular/platform-browser/platform-browser"' has no exported member 'DOCUMENT'.

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/new **
ℹ ｢wdm｣: Failed to compile.

**Comment by sea-kg** [comment]
Please merge from master previously... I suppose that problems migrate from angular 7 to angular 8 (

**Comment by sea-kg** [comment]
Please create new page user-skills and add to user-profile-menu  new point "skills"

**Pull request merged**
